version: '3'

networks:
  test_task-network:
    driver: bridge

services:

        test_task:
            container_name: test_task
            build:
                context: ./php-fpm
                args:
                    - timezone=${TZ}
            networks:
                - test_task-network
            ports:
                - "9000:9000"
            volumes:
                - ./../test_task:/test_task:rw,cached
                - test_task_log:/test_task/var/log
            env_file:
                - .env
            depends_on:
                - redis
                - memcached
                - db-master

        nginx:
            container_name: nginx
            build:
                context: ./nginx
                args:
                    - timezone=${TZ}
            ports:
                - "81:80"
                - "443:443"
            networks:
                - test_task-network
            depends_on:
                - test_task
            volumes:
                - ./../test_task/public:/test_task/public
                - ./nginx/ssl:/etc/nginx/ssl
                - ./nginx/conf.d:/etc/nginx/conf.d
                - ./nginx/nginx_log:/var/log/nginx
                - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            env_file:
                - .env
            command: /bin/bash -c "exec nginx -g 'daemon off;'"

        redis:
            container_name: redis
            image: redis:latest
            networks:
                - test_task-network

        memcached:
            container_name: memcached
            image: memcached:latest
            networks:
                - test_task-network

        db-master:
            container_name: db-master
            image: mysql:latest
            env_file:
                - ./db/master/.env.master
            ports:
                - "4406:3306"
            volumes:
                - ./db/master/master.sql:/docker-entrypoint-initdb.d/start.sql
                - ./db/master/mysql.master.cnf:/etc/mysql/conf.d/mysql.master.cnf
                - ./db/master/.data/mysql:/var/lib/mysql:rw
            networks:
                - test_task-network

volumes:
    nginx_log:
    test_task_log:
    db:
        driver: local

